### ISSUE TITLE
5.4.10 introduced large sound file

### ISSUE THREAD

**Issue by jjatria** [jjatria/praat#1]
In the sources for 5.4.10, a _very_ large file exists in [`dwtest/tone.wav`](http://www.fon.hum.uva.nl/praat/old/src//sources_5410/dwtest/tone.wav). The file is about 170M in size!

This mirror **does not have that file**, because Github [does not allow for the upload of files larger than 100M](https://help.github.com/articles/working-with-large-files/). You can download it yourself from the link above if you must.

**Comment by PaulBoersma** [comment]
The file was there by mistake.

**Comment by jjatria** [comment]
Good to know! Recent versions of the source code no longer have this file, which means this mirror is now an actual mirror, and this issue can be closed.
